apiVersion: v1
kind: Pod
metadata:
  name: tester
spec:
  restartPolicy: OnFailure
  containers:
  - name: ytentry
    image: {{ .Values.SystestImagePath }}
    imagePullPolicy: Always
    env:
    - name: YT_CONFIG_PATCHES
      value: '{proxy={enable_proxy_discovery=%false}}'
    - name: YT_TOKEN
      value: 'password'
    - name: YT_PROXY
      value: "$(HTTP_PROXIES_LB_SERVICE_HOST):$(HTTP_PROXIES_LB_SERVICE_PORT)"
    command: ['bash', '/usr/bin/init.sh']
