on:
  workflow_call:
    inputs:
      runs-on-value:
        required: true
        type: string
      build-strawberry:
        default: false
        required: false
        type: boolean
      build-ytsaurus:
        default: false
        required: false
        type: boolean
      build-chyt:
        default: false
        required: false
        type: boolean
      build-query-tracker:
        default: false
        required: false
        type: boolean
      build-query-tracker-ya-make:
        default: false
        required: false
        type: boolean
      build-python:
        default: false
        required: false
        type: boolean

jobs:
  build:
    runs-on: ${{ inputs.runs-on-value }}
    steps:
      - name: Prepare python virtual environment
        run: |
          python3.11 -m venv ../venv

      - name: Build strawberry controller
        if: ${{ inputs.build-strawberry }}
        run: |
          cd ../ytsaurus/ytsaurus/yt/chyt/controller/cmd/chyt-controller
          export HOME=${RUNNER_WORKSPACE}
          /opt/go/bin/go build

      - name: Configure ytsaurus
        if: ${{ inputs.build-ytsaurus || inputs.build-chyt || inputs.build-query-tracker }}
        run: |
          mkdir -p ../build
          cd ../build
          rm -rf *
          cmake \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=../ytsaurus/ytsaurus/clang.toolchain \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            ../ytsaurus/ytsaurus

      - name: Configure ytsaurus (relwithdebinfo)
        if: ${{ inputs.build-ytsaurus || inputs.build-chyt || inputs.build-query-tracker }}
        run: |
          mkdir -p ../build_relwithdebinfo
          cd ../build_relwithdebinfo
          rm -rf *
          cmake \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_TOOLCHAIN_FILE=../ytsaurus/ytsaurus/clang.toolchain \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            ../ytsaurus/ytsaurus

      - name: Configure query tracker
        if: ${{ inputs.build-query-tracker }}
        run: |
          #TODO: install it inside vm image.
          sudo apt-get -y install antlr3 libaio1 libaio-dev

          #TODO: remove -DMKQL_DISABLE_CODEGEN after YT-19852.
          mkdir -p ../build_qt
          cd ../build_qt
          rm -rf *
          cmake \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER_LAUNCHER=/usr/local/bin/ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=/usr/local/bin/ccache \
            -DCMAKE_TOOLCHAIN_FILE=../ytsaurus/ydb/clang.toolchain \
            -DCMAKE_C_FLAGS_RELEASE="-O2 -UNDEBUG -DMKQL_DISABLE_CODEGEN" \
            -DCMAKE_CXX_FLAGS_RELEASE="-O2 -UNDEBUG -DMKQL_DISABLE_CODEGEN" \
            -DCMAKE_C_FLAGS="-O2 -UNDEBUG -DMKQL_DISABLE_CODEGEN" \
            -DCMAKE_CXX_FLAGS="-O2 -UNDEBUG -DMKQL_DISABLE_CODEGEN" \
            -DCMAKE_POSITION_INDEPENDENT_CODE=On \
            ../ytsaurus/ydb

      - name: Configure query tracker (relwithdebinfo)
        if: ${{ inputs.build-query-tracker }}
        run: |
          mkdir -p ../build_qt_relwithdebinfo
          cd ../build_qt_relwithdebinfo
          rm -rf *
          cmake \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_C_COMPILER_LAUNCHER=/usr/local/bin/ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=/usr/local/bin/ccache \
            -DCMAKE_TOOLCHAIN_FILE=../ytsaurus/ydb/clang.toolchain \
            -DCMAKE_C_FLAGS="-O2 -UNDEBUG -DMKQL_DISABLE_CODEGEN" \
            -DCMAKE_CXX_FLAGS="-O2 -UNDEBUG -DMKQL_DISABLE_CODEGEN" \
            -DCMAKE_C_FLAGS_RELWITHDEBINFO="-O2 -UNDEBUG -DMKQL_DISABLE_CODEGEN" \
            -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-O2 -UNDEBUG -DMKQL_DISABLE_CODEGEN" \
            -DCMAKE_POSITION_INDEPENDENT_CODE=On \
            ../ytsaurus/ydb

      - name: Build ytsaurus
        if: ${{ inputs.build-ytsaurus || inputs.build-chyt || inputs.build-query-tracker }}
        run: |
          export CCACHE_BASEDIR="$(realpath ..)"
          export CCACHE_REMOTE_ONLY=true
          export CCACHE_REMOTE_STORAGE="${{ vars.CCACHE_REMOTE_STORAGE }}"

          cd ../build
          ninja

          cd ../build_relwithdebinfo
          ninja ytserver-all

      - name: Build ytsaurus (ya make, relwithdebinfo)
        if: ${{ inputs.build-query-tracker-ya-make }}
        run: |
          mkdir -p ../ya_build
          cd ../ya_build
          rm -rf *

          # Check build.
          ../ytsaurus/ytsaurus/ya make -T --build=relwithdebinfo  --output=../ya_build ../ytsaurus/ytsaurus/yt/yt
          # Check python tests.
          ../ytsaurus/ytsaurus/ya make -T --build=relwithdebinfo  --output=../ya_build ../ytsaurus/ytsaurus/yt/python/yt/wrapper/tests --run-all-tests -F "*test_get_set_exists*"
          # Check integration tests.
          ../ytsaurus/ytsaurus/ya make -T --build=relwithdebinfo  --output=../ya_build ../ytsaurus/ytsaurus/yt/yt/tests/integration/scheduler --run-all-tests -F "*TestMultipleSchedulers*"

      - name: Build chyt
        if: ${{ inputs.build-chyt }}
        run: |
          export CCACHE_BASEDIR="$(realpath ..)"
          export CCACHE_REMOTE_ONLY=true
          export CCACHE_REMOTE_STORAGE="${{ vars.CCACHE_REMOTE_STORAGE }}"

          cd ../build_relwithdebinfo
          ninja ytserver-clickhouse

      - name: Build query tracker
        if: ${{ inputs.build-query-tracker }}
        run: |
          export CCACHE_BASEDIR="$(realpath ..)"
          export CCACHE_REMOTE_ONLY=true
          export CCACHE_REMOTE_STORAGE="${{ vars.CCACHE_REMOTE_STORAGE }}"

          for dir in build_qt build_qt_relwithdebinfo ; do
              cd ../${dir}
              ninja libcompress_udf.so
              ninja libdatetime2_udf.so
              ninja libdigest_udf.so
              ninja libdsv_udf.so
              ninja libfile_udf.so
              ninja libhistogram_udf.so
              ninja libhyperloglog_udf.so
              ninja libhyperscan_udf.so
              ninja libip_udf.so
              ninja libjson2_udf.so
              ninja libjson_udf.so
              ninja libmath_udf.so
              ninja libpire_udf.so
              ninja libprotobuf_udf.so
              ninja libre2_udf.so
              ninja libset_udf.so
              ninja libstat_udf.so
              ninja libstreaming_udf.so
              ninja libstring_udf.so
              ninja libtopfreq_udf.so
              ninja libtop_udf.so
              ninja libunicode_udf.so
              ninja liburl_udf.so
              ninja libyqlplugin.so
              ninja libyson2_udf.so
              ninja mrjob
          done

          cd ../build_relwithdebinfo
          ninja ytserver-yql-agent

      - name: Build query tracker (ya make, relwithdebinfo)
        if: ${{ inputs.build-query-tracker-ya-make }}
        run: |
          mkdir -p ../build_qt_ya_make
          cd ../build_qt_ya_make
          rm -rf *

          ../ytsaurus/ytsaurus/ya make -T --build=relwithdebinfo  --output=../ya_build ../ytsaurus/ytsaurus/yt/yql/agent/bin

          shopt -s expand_aliases
          alias ydb-ya-make="../ytsaurus/ydb/ya make -T --ignore-recurses --build=relwithdebinfo  --output=."

          ydb-ya-make ../ytsaurus/ydb/ydb/library/yql/tools/mrjob
          ydb-ya-make ../ytsaurus/ydb/ydb/library/yql/yt/dynamic

          udfs_prefix="../ytsaurus/ydb/ydb/library/yql/udfs/common"
          ydb-ya-make ${udfs_prefix}/compress_base
          ydb-ya-make ${udfs_prefix}/datetime2
          ydb-ya-make ${udfs_prefix}/digest
          ydb-ya-make ${udfs_prefix}/file
          ydb-ya-make ${udfs_prefix}/histogram
          ydb-ya-make ${udfs_prefix}/hyperloglog
          ydb-ya-make ${udfs_prefix}/hyperscan
          ydb-ya-make ${udfs_prefix}/ip_base
          ydb-ya-make ${udfs_prefix}/json
          ydb-ya-make ${udfs_prefix}/json2
          ydb-ya-make ${udfs_prefix}/math
          ydb-ya-make ${udfs_prefix}/pire
          ydb-ya-make ${udfs_prefix}/protobuf
          ydb-ya-make ${udfs_prefix}/re2
          ydb-ya-make ${udfs_prefix}/set
          ydb-ya-make ${udfs_prefix}/stat
          ydb-ya-make ${udfs_prefix}/streaming
          ydb-ya-make ${udfs_prefix}/string
          ydb-ya-make ${udfs_prefix}/top
          ydb-ya-make ${udfs_prefix}/topfreq
          ydb-ya-make ${udfs_prefix}/unicode_base
          ydb-ya-make ${udfs_prefix}/url_base
          ydb-ya-make ${udfs_prefix}/yson2

          ydb-ya-make ../ytsaurus/ydb/ydb/library/yql/udfs/logs/dsv

      - name: Build Python packages
        if: ${{ inputs.build-python }}
        run: |
          source ../venv/bin/activate
          if ${{ inputs.build-query-tracker-ya-make }}; then
            YTSAURUS_COMMIT_HASH=${GITHUB_SHA} bash ./ytsaurus/yt/python/packages/build_ytsaurus_packages.sh --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../ya_build --not-prepare-bindings-libraries
          else
            YTSAURUS_COMMIT_HASH=${GITHUB_SHA} bash ./ytsaurus/yt/python/packages/build_ytsaurus_packages.sh --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build
          fi

